FROM --platform=linux ubuntu:22.04
ARG BUILDARCH

# Change your versions here
ENV GO_VERSION=1.18.3
ENV IGNITE_VERSION=0.22.1
ENV NODE_VERSION=18.x
ENV MOCKGEN_VERSION=1.6.0

ENV LOCAL=/usr/local
ENV GOROOT=$LOCAL/go
ENV HOME=/root
ENV GOPATH=$HOME/go
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH

RUN mkdir -p $GOPATH/bin

ENV PACKAGES curl gcc jq make
RUN apt-get update
RUN apt-get install -y $PACKAGES

# Install Go
RUN curl -L https://go.dev/dl/go${GO_VERSION}.linux-$BUILDARCH.tar.gz | tar -C $LOCAL -xzf -

# Install Ignite
RUN curl -L https://get.ignite.com/cli@v${IGNITE_VERSION}! | bash

# Install Node
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash -
RUN apt-get install -y nodejs

# Install Mockgen
RUN go install github.com/golang/mock/mockgen@v${MOCKGEN_VERSION}

#WORKDIR /home/hub
WORKDIR /hub

# Copy local repository
#ADD hub /home/hub

# Copy serve script
#COPY ./run-hub.sh /hub
#RUN chmod +x ./run-hub.sh

#RUN chmod +x ./hub/run-hub.sh

#ENTRYPOINT ["/bin/bash", "-c", "/hub/run-hub.sh"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]

ENTRYPOINT ["/bin/bash", "-c", "./run-hub.sh"]


EXPOSE 26657 1317 4500