version: "3.7"

networks:
  net-it:
  net-de:
  net-public:

services:

  val-unipi:
    command: start
    container_name: val-unipi
    image: university_chain_itd_i
    networks:
      - net-it
      - net-public
    ports:
      - 0.0.0.0:26650:26657
    volumes:
      - ./university_chain_it/elements/val-unipi:/root/.university_chain_it
      

  val-uniroma1:
    command: start
    container_name: val-uniroma1
    image: university_chain_itd_i
    networks:
      - net-it
      - net-public
    ports:
      - 0.0.0.0:26651:26657
    volumes:
      - ./university_chain_it/elements/val-uniroma1:/root/.university_chain_it
      
  val-tum:
    command: start
    container_name: val-tum
    image: university_chain_ded_i
    networks:
      - net-de
      - net-public
    ports:
      - 0.0.0.0:26652:26657
    volumes:
      - ./university_chain_de/elements/val-tum:/root/.university_chain_de	
      

  val-humboldt:
    command: start
    container_name: val-humboldt
    image: university_chain_ded_i
    networks:
      - net-de
      - net-public
    ports:
      - 0.0.0.0:26653:26657
    volumes:
      - ./university_chain_de/elements/val-humboldt:/root/.university_chain_de
      
  val-hub:
    command: start
    container_name: val-hub
    image: "hubd_i"
    networks:
      - net-public
    ports:
      - 0.0.0.0:26654:26657
    volumes:
      - ./hub/elements/val-hub:/root/.hub

      
  go_relayer_it_hub:
    profiles: ["go"]
    container_name: go_relayer_it_hub
    image: "go_relayer_it_hub"
    tty: true
    stdin_open: true
    networks:
      - net-public
    volumes:
      - ./go_relayer_it_hub:/go_relayer_it_hub
      
  hermes_relayer_it_hub:
    profiles: ["hermes"]
    container_name: hermes_relayer_it_hub
    image: "hermes_relayer_it_hub"
    tty: true
    stdin_open: true
    networks:
      - net-public
    volumes:
      - ./hermes_relayer_it_hub:/hermes_relayer_it_hub
      

