# start with docker-compose -f modular.yml up -d

version: '3'

services:

  hub:
    container_name: hub
    image: "hub"

    ports:
      - "26656:26657"
      - "1316:1317"
      - "4499:4500"
    volumes:
      - ./hub:/hub
    networks:
      - erasmusdemo

  university_chain_it:
    container_name: university_chain_it
    image: "university_chain_it"

    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"
    volumes:
      - ./university_chain_it:/university_chain_it
    networks:
      - erasmusdemo

  go_relayer_it_hub:
    profiles: ["go"]
    container_name: go_relayer_it_hub
    image: "go_relayer_it_hub"
    tty: true
    stdin_open: true
    volumes:
      - ./go_relayer_it_hub:/go_relayer_it_hub
    networks:
      - erasmusdemo

      

  hermes_relayer_it_hub:
    profiles: ["hermes"]
    container_name: hermes_relayer_it_hub
    image: "hermes_relayer_it_hub"
    tty: true
    stdin_open: true
    volumes:
      - ./hermes_relayer_it_hub:/hermes_relayer_it_hub
    networks:
      - erasmusdemo
      
  university_chain_de:
    container_name: university_chain_de
    image: "university_chain_de"

    ports:
      - "26658:26657"
      - "1318:1317"
      - "4501:4500"
    volumes:
      - ./university_chain_de:/university_chain_de
    networks:
      - erasmusdemo

  go_relayer_de_hub:
    profiles: ["go"]
    container_name: go_relayer_de_hub
    image: "go_relayer_de_hub"
    tty: true
    stdin_open: true
    volumes:
      - ./go_relayer_de_hub:/go_relayer_de_hub
    networks:
      - erasmusdemo

  hermes_relayer_de_hub:
    profiles: ["hermes"]
    container_name: hermes_relayer_de_hub
    image: "hermes_relayer_de_hub"
    tty: true
    stdin_open: true
    volumes:
      - ./hermes_relayer_de_hub:/hermes_relayer_de_hub
    networks:
      - erasmusdemo

networks:
    erasmusdemo:
