// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/foreign_universities.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ForeignUniversities struct {
	UniversityName             string `protobuf:"bytes,1,opt,name=universityName,proto3" json:"universityName,omitempty"`
	ForeignUniversitiesKey     string `protobuf:"bytes,2,opt,name=foreignUniversitiesKey,proto3" json:"foreignUniversitiesKey,omitempty"`
	ForeignUniversitiesCountry string `protobuf:"bytes,3,opt,name=foreignUniversitiesCountry,proto3" json:"foreignUniversitiesCountry,omitempty"`
}

func (m *ForeignUniversities) Reset()         { *m = ForeignUniversities{} }
func (m *ForeignUniversities) String() string { return proto.CompactTextString(m) }
func (*ForeignUniversities) ProtoMessage()    {}
func (*ForeignUniversities) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05ece0580f4dc8d, []int{0}
}
func (m *ForeignUniversities) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForeignUniversities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForeignUniversities.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForeignUniversities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForeignUniversities.Merge(m, src)
}
func (m *ForeignUniversities) XXX_Size() int {
	return m.Size()
}
func (m *ForeignUniversities) XXX_DiscardUnknown() {
	xxx_messageInfo_ForeignUniversities.DiscardUnknown(m)
}

var xxx_messageInfo_ForeignUniversities proto.InternalMessageInfo

func (m *ForeignUniversities) GetUniversityName() string {
	if m != nil {
		return m.UniversityName
	}
	return ""
}

func (m *ForeignUniversities) GetForeignUniversitiesKey() string {
	if m != nil {
		return m.ForeignUniversitiesKey
	}
	return ""
}

func (m *ForeignUniversities) GetForeignUniversitiesCountry() string {
	if m != nil {
		return m.ForeignUniversitiesCountry
	}
	return ""
}

func init() {
	proto.RegisterType((*ForeignUniversities)(nil), "university_chain_it.universitychainit.ForeignUniversities")
}

func init() {
	proto.RegisterFile("universitychainit/foreign_universities.proto", fileDescriptor_d05ece0580f4dc8d)
}

var fileDescriptor_d05ece0580f4dc8d = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x29, 0xcd, 0xcb, 0x2c,
	0x4b, 0x2d, 0x2a, 0xce, 0x2c, 0xa9, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xcb, 0x2c, 0xd1, 0x4f, 0xcb,
	0x2f, 0x4a, 0xcd, 0x4c, 0xcf, 0x8b, 0x87, 0xcb, 0x64, 0xa6, 0x16, 0xeb, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0xa9, 0x22, 0x54, 0xc7, 0x83, 0x95, 0xc7, 0x67, 0x96, 0xe8, 0x61, 0x98, 0xa0, 0xb4,
	0x95, 0x91, 0x4b, 0xd8, 0x0d, 0x62, 0x4a, 0x28, 0x92, 0x21, 0x42, 0x6a, 0x5c, 0x7c, 0x08, 0xc5,
	0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x68, 0xa2, 0x42, 0x66, 0x5c,
	0x62, 0x69, 0x98, 0xda, 0xbd, 0x53, 0x2b, 0x25, 0x98, 0xc0, 0xea, 0x71, 0xc8, 0x0a, 0xd9, 0x71,
	0x49, 0x61, 0x91, 0x71, 0xce, 0x2f, 0xcd, 0x2b, 0x29, 0xaa, 0x94, 0x60, 0x06, 0xeb, 0xc5, 0xa3,
	0xc2, 0xc9, 0xfd, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c,
	0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x74, 0xb1, 0x78,
	0x5c, 0xbf, 0x42, 0x1f, 0x33, 0xf0, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xc1, 0x65,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x83, 0x15, 0xe3, 0x5e, 0x01, 0x00, 0x00,
}

func (m *ForeignUniversities) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForeignUniversities) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForeignUniversities) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ForeignUniversitiesCountry) > 0 {
		i -= len(m.ForeignUniversitiesCountry)
		copy(dAtA[i:], m.ForeignUniversitiesCountry)
		i = encodeVarintForeignUniversities(dAtA, i, uint64(len(m.ForeignUniversitiesCountry)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ForeignUniversitiesKey) > 0 {
		i -= len(m.ForeignUniversitiesKey)
		copy(dAtA[i:], m.ForeignUniversitiesKey)
		i = encodeVarintForeignUniversities(dAtA, i, uint64(len(m.ForeignUniversitiesKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UniversityName) > 0 {
		i -= len(m.UniversityName)
		copy(dAtA[i:], m.UniversityName)
		i = encodeVarintForeignUniversities(dAtA, i, uint64(len(m.UniversityName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintForeignUniversities(dAtA []byte, offset int, v uint64) int {
	offset -= sovForeignUniversities(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ForeignUniversities) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UniversityName)
	if l > 0 {
		n += 1 + l + sovForeignUniversities(uint64(l))
	}
	l = len(m.ForeignUniversitiesKey)
	if l > 0 {
		n += 1 + l + sovForeignUniversities(uint64(l))
	}
	l = len(m.ForeignUniversitiesCountry)
	if l > 0 {
		n += 1 + l + sovForeignUniversities(uint64(l))
	}
	return n
}

func sovForeignUniversities(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozForeignUniversities(x uint64) (n int) {
	return sovForeignUniversities(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ForeignUniversities) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowForeignUniversities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForeignUniversities: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForeignUniversities: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowForeignUniversities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignUniversitiesKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowForeignUniversities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignUniversitiesKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignUniversitiesCountry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowForeignUniversities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignUniversitiesCountry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipForeignUniversities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthForeignUniversities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipForeignUniversities(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowForeignUniversities
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowForeignUniversities
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowForeignUniversities
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthForeignUniversities
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupForeignUniversities
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthForeignUniversities
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthForeignUniversities        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowForeignUniversities          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupForeignUniversities = fmt.Errorf("proto: unexpected end of group")
)
