// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UniversitychainitPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*UniversitychainitPacketData_NoData
	//	*UniversitychainitPacketData_EndErasmusPeriodRequestPacket
	//	*UniversitychainitPacketData_ErasmusIndexPacket
	//	*UniversitychainitPacketData_ErasmusStudentPacket
	Packet isUniversitychainitPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *UniversitychainitPacketData) Reset()         { *m = UniversitychainitPacketData{} }
func (m *UniversitychainitPacketData) String() string { return proto.CompactTextString(m) }
func (*UniversitychainitPacketData) ProtoMessage()    {}
func (*UniversitychainitPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{0}
}
func (m *UniversitychainitPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UniversitychainitPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UniversitychainitPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UniversitychainitPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversitychainitPacketData.Merge(m, src)
}
func (m *UniversitychainitPacketData) XXX_Size() int {
	return m.Size()
}
func (m *UniversitychainitPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversitychainitPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_UniversitychainitPacketData proto.InternalMessageInfo

type isUniversitychainitPacketData_Packet interface {
	isUniversitychainitPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type UniversitychainitPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type UniversitychainitPacketData_EndErasmusPeriodRequestPacket struct {
	EndErasmusPeriodRequestPacket *EndErasmusPeriodRequestPacketData `protobuf:"bytes,4,opt,name=endErasmusPeriodRequestPacket,proto3,oneof" json:"endErasmusPeriodRequestPacket,omitempty"`
}
type UniversitychainitPacketData_ErasmusIndexPacket struct {
	ErasmusIndexPacket *ErasmusIndexPacketData `protobuf:"bytes,3,opt,name=erasmusIndexPacket,proto3,oneof" json:"erasmusIndexPacket,omitempty"`
}
type UniversitychainitPacketData_ErasmusStudentPacket struct {
	ErasmusStudentPacket *ErasmusStudentPacketData `protobuf:"bytes,2,opt,name=erasmusStudentPacket,proto3,oneof" json:"erasmusStudentPacket,omitempty"`
}

func (*UniversitychainitPacketData_NoData) isUniversitychainitPacketData_Packet() {}
func (*UniversitychainitPacketData_EndErasmusPeriodRequestPacket) isUniversitychainitPacketData_Packet() {
}
func (*UniversitychainitPacketData_ErasmusIndexPacket) isUniversitychainitPacketData_Packet()   {}
func (*UniversitychainitPacketData_ErasmusStudentPacket) isUniversitychainitPacketData_Packet() {}

func (m *UniversitychainitPacketData) GetPacket() isUniversitychainitPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *UniversitychainitPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*UniversitychainitPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *UniversitychainitPacketData) GetEndErasmusPeriodRequestPacket() *EndErasmusPeriodRequestPacketData {
	if x, ok := m.GetPacket().(*UniversitychainitPacketData_EndErasmusPeriodRequestPacket); ok {
		return x.EndErasmusPeriodRequestPacket
	}
	return nil
}

func (m *UniversitychainitPacketData) GetErasmusIndexPacket() *ErasmusIndexPacketData {
	if x, ok := m.GetPacket().(*UniversitychainitPacketData_ErasmusIndexPacket); ok {
		return x.ErasmusIndexPacket
	}
	return nil
}

func (m *UniversitychainitPacketData) GetErasmusStudentPacket() *ErasmusStudentPacketData {
	if x, ok := m.GetPacket().(*UniversitychainitPacketData_ErasmusStudentPacket); ok {
		return x.ErasmusStudentPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UniversitychainitPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UniversitychainitPacketData_NoData)(nil),
		(*UniversitychainitPacketData_EndErasmusPeriodRequestPacket)(nil),
		(*UniversitychainitPacketData_ErasmusIndexPacket)(nil),
		(*UniversitychainitPacketData_ErasmusStudentPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// ErasmusStudentPacketData defines a struct for the packet payload
type ErasmusStudentPacketData struct {
	Student *StoredStudent `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
}

func (m *ErasmusStudentPacketData) Reset()         { *m = ErasmusStudentPacketData{} }
func (m *ErasmusStudentPacketData) String() string { return proto.CompactTextString(m) }
func (*ErasmusStudentPacketData) ProtoMessage()    {}
func (*ErasmusStudentPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{2}
}
func (m *ErasmusStudentPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusStudentPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusStudentPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusStudentPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusStudentPacketData.Merge(m, src)
}
func (m *ErasmusStudentPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusStudentPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusStudentPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusStudentPacketData proto.InternalMessageInfo

func (m *ErasmusStudentPacketData) GetStudent() *StoredStudent {
	if m != nil {
		return m.Student
	}
	return nil
}

// ErasmusStudentPacketAck defines a struct for the packet acknowledgment
type ErasmusStudentPacketAck struct {
	Index                  string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ForeignIndex           string `protobuf:"bytes,2,opt,name=foreignIndex,proto3" json:"foreignIndex,omitempty"`
	StartingUniversityName string `protobuf:"bytes,3,opt,name=starting_university_name,json=startingUniversityName,proto3" json:"starting_university_name,omitempty"`
}

func (m *ErasmusStudentPacketAck) Reset()         { *m = ErasmusStudentPacketAck{} }
func (m *ErasmusStudentPacketAck) String() string { return proto.CompactTextString(m) }
func (*ErasmusStudentPacketAck) ProtoMessage()    {}
func (*ErasmusStudentPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{3}
}
func (m *ErasmusStudentPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusStudentPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusStudentPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusStudentPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusStudentPacketAck.Merge(m, src)
}
func (m *ErasmusStudentPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusStudentPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusStudentPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusStudentPacketAck proto.InternalMessageInfo

func (m *ErasmusStudentPacketAck) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ErasmusStudentPacketAck) GetForeignIndex() string {
	if m != nil {
		return m.ForeignIndex
	}
	return ""
}

func (m *ErasmusStudentPacketAck) GetStartingUniversityName() string {
	if m != nil {
		return m.StartingUniversityName
	}
	return ""
}

// ErasmusIndexPacketData defines a struct for the packet payload
type ErasmusIndexPacketData struct {
	Index        string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ForeignIndex string `protobuf:"bytes,2,opt,name=foreignIndex,proto3" json:"foreignIndex,omitempty"`
}

func (m *ErasmusIndexPacketData) Reset()         { *m = ErasmusIndexPacketData{} }
func (m *ErasmusIndexPacketData) String() string { return proto.CompactTextString(m) }
func (*ErasmusIndexPacketData) ProtoMessage()    {}
func (*ErasmusIndexPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{4}
}
func (m *ErasmusIndexPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusIndexPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusIndexPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusIndexPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusIndexPacketData.Merge(m, src)
}
func (m *ErasmusIndexPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusIndexPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusIndexPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusIndexPacketData proto.InternalMessageInfo

func (m *ErasmusIndexPacketData) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ErasmusIndexPacketData) GetForeignIndex() string {
	if m != nil {
		return m.ForeignIndex
	}
	return ""
}

// ErasmusIndexPacketAck defines a struct for the packet acknowledgment
type ErasmusIndexPacketAck struct {
}

func (m *ErasmusIndexPacketAck) Reset()         { *m = ErasmusIndexPacketAck{} }
func (m *ErasmusIndexPacketAck) String() string { return proto.CompactTextString(m) }
func (*ErasmusIndexPacketAck) ProtoMessage()    {}
func (*ErasmusIndexPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{5}
}
func (m *ErasmusIndexPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusIndexPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusIndexPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusIndexPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusIndexPacketAck.Merge(m, src)
}
func (m *ErasmusIndexPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusIndexPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusIndexPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusIndexPacketAck proto.InternalMessageInfo

// EndErasmusPeriodRequestPacketData defines a struct for the packet payload
type EndErasmusPeriodRequestPacketData struct {
	StartingUniversityName    string `protobuf:"bytes,1,opt,name=startingUniversityName,proto3" json:"startingUniversityName,omitempty"`
	DestinationUniversityName string `protobuf:"bytes,2,opt,name=destinationUniversityName,proto3" json:"destinationUniversityName,omitempty"`
	Index                     string `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	ForeignIndex              string `protobuf:"bytes,4,opt,name=foreignIndex,proto3" json:"foreignIndex,omitempty"`
}

func (m *EndErasmusPeriodRequestPacketData) Reset()         { *m = EndErasmusPeriodRequestPacketData{} }
func (m *EndErasmusPeriodRequestPacketData) String() string { return proto.CompactTextString(m) }
func (*EndErasmusPeriodRequestPacketData) ProtoMessage()    {}
func (*EndErasmusPeriodRequestPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{6}
}
func (m *EndErasmusPeriodRequestPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EndErasmusPeriodRequestPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EndErasmusPeriodRequestPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EndErasmusPeriodRequestPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndErasmusPeriodRequestPacketData.Merge(m, src)
}
func (m *EndErasmusPeriodRequestPacketData) XXX_Size() int {
	return m.Size()
}
func (m *EndErasmusPeriodRequestPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_EndErasmusPeriodRequestPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_EndErasmusPeriodRequestPacketData proto.InternalMessageInfo

func (m *EndErasmusPeriodRequestPacketData) GetStartingUniversityName() string {
	if m != nil {
		return m.StartingUniversityName
	}
	return ""
}

func (m *EndErasmusPeriodRequestPacketData) GetDestinationUniversityName() string {
	if m != nil {
		return m.DestinationUniversityName
	}
	return ""
}

func (m *EndErasmusPeriodRequestPacketData) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *EndErasmusPeriodRequestPacketData) GetForeignIndex() string {
	if m != nil {
		return m.ForeignIndex
	}
	return ""
}

// EndErasmusPeriodRequestPacketAck defines a struct for the packet acknowledgment
type EndErasmusPeriodRequestPacketAck struct {
	ErasmusData *ErasmusInfo `protobuf:"bytes,1,opt,name=erasmusData,proto3" json:"erasmusData,omitempty"`
	HomeIndex   string       `protobuf:"bytes,2,opt,name=homeIndex,proto3" json:"homeIndex,omitempty"`
}

func (m *EndErasmusPeriodRequestPacketAck) Reset()         { *m = EndErasmusPeriodRequestPacketAck{} }
func (m *EndErasmusPeriodRequestPacketAck) String() string { return proto.CompactTextString(m) }
func (*EndErasmusPeriodRequestPacketAck) ProtoMessage()    {}
func (*EndErasmusPeriodRequestPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c790adb4d4f2cf6, []int{7}
}
func (m *EndErasmusPeriodRequestPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EndErasmusPeriodRequestPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EndErasmusPeriodRequestPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EndErasmusPeriodRequestPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndErasmusPeriodRequestPacketAck.Merge(m, src)
}
func (m *EndErasmusPeriodRequestPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *EndErasmusPeriodRequestPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EndErasmusPeriodRequestPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_EndErasmusPeriodRequestPacketAck proto.InternalMessageInfo

func (m *EndErasmusPeriodRequestPacketAck) GetErasmusData() *ErasmusInfo {
	if m != nil {
		return m.ErasmusData
	}
	return nil
}

func (m *EndErasmusPeriodRequestPacketAck) GetHomeIndex() string {
	if m != nil {
		return m.HomeIndex
	}
	return ""
}

func init() {
	proto.RegisterType((*UniversitychainitPacketData)(nil), "university_chain_it.universitychainit.UniversitychainitPacketData")
	proto.RegisterType((*NoData)(nil), "university_chain_it.universitychainit.NoData")
	proto.RegisterType((*ErasmusStudentPacketData)(nil), "university_chain_it.universitychainit.ErasmusStudentPacketData")
	proto.RegisterType((*ErasmusStudentPacketAck)(nil), "university_chain_it.universitychainit.ErasmusStudentPacketAck")
	proto.RegisterType((*ErasmusIndexPacketData)(nil), "university_chain_it.universitychainit.ErasmusIndexPacketData")
	proto.RegisterType((*ErasmusIndexPacketAck)(nil), "university_chain_it.universitychainit.ErasmusIndexPacketAck")
	proto.RegisterType((*EndErasmusPeriodRequestPacketData)(nil), "university_chain_it.universitychainit.EndErasmusPeriodRequestPacketData")
	proto.RegisterType((*EndErasmusPeriodRequestPacketAck)(nil), "university_chain_it.universitychainit.EndErasmusPeriodRequestPacketAck")
}

func init() { proto.RegisterFile("universitychainit/packet.proto", fileDescriptor_8c790adb4d4f2cf6) }

var fileDescriptor_8c790adb4d4f2cf6 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x63, 0x52, 0x42, 0x33, 0xe5, 0x64, 0x95, 0x36, 0x14, 0x58, 0x15, 0x0b, 0x10, 0x97,
	0x26, 0x52, 0x41, 0x88, 0x03, 0x08, 0xb5, 0xa2, 0x6a, 0xb9, 0x44, 0x95, 0x0b, 0x17, 0x2e, 0x2b,
	0x93, 0x9d, 0xb4, 0x26, 0x8a, 0x1d, 0xd6, 0x5e, 0xd4, 0x3e, 0x04, 0x52, 0x4f, 0x3c, 0x13, 0xc7,
	0x4a, 0x5c, 0x38, 0xa2, 0xe4, 0xc8, 0x4b, 0xa0, 0x78, 0x5d, 0x25, 0xed, 0x7e, 0xb0, 0xe1, 0x96,
	0xd8, 0x33, 0xff, 0xdf, 0x7f, 0x3e, 0xd6, 0x10, 0x24, 0x4a, 0x7e, 0xc5, 0xd8, 0x48, 0x7b, 0xd6,
	0x3b, 0x11, 0x52, 0x49, 0xdb, 0x19, 0x89, 0xde, 0x00, 0x6d, 0x7b, 0x14, 0x6b, 0xab, 0xe9, 0xe3,
	0xd9, 0x7d, 0xe8, 0x02, 0x42, 0x69, 0xdb, 0x99, 0x9c, 0x8d, 0x27, 0x59, 0x19, 0x63, 0x75, 0x8c,
	0x51, 0x68, 0x6c, 0x12, 0xa1, 0xf2, 0x72, 0x1b, 0x8f, 0xb2, 0x71, 0x18, 0x0b, 0x33, 0x4c, 0x4c,
	0x28, 0x55, 0x5f, 0xa7, 0x51, 0xec, 0x4f, 0x1d, 0xee, 0x7d, 0xb8, 0x1e, 0x78, 0xe8, 0x6c, 0xbd,
	0x15, 0x56, 0xd0, 0x7d, 0x68, 0x28, 0x3d, 0xfd, 0xd5, 0x22, 0x9b, 0xe4, 0xe9, 0xca, 0xf6, 0x56,
	0xbb, 0x92, 0xcb, 0x76, 0xd7, 0x25, 0x1d, 0xd4, 0xb8, 0x4f, 0xa7, 0xe7, 0x04, 0x1e, 0xa0, 0x8a,
	0xf6, 0x52, 0x0b, 0x87, 0x18, 0x4b, 0x1d, 0x71, 0xfc, 0x92, 0xa0, 0xf1, 0xb8, 0xd6, 0x92, 0x03,
	0x1c, 0x54, 0x04, 0xec, 0x95, 0x69, 0x79, 0x76, 0x39, 0x90, 0x6a, 0xa0, 0xbe, 0x23, 0xef, 0x54,
	0x84, 0xa7, 0xde, 0x46, 0xdd, 0xd9, 0x78, 0x5d, 0xd5, 0x46, 0x46, 0xc0, 0xb3, 0x73, 0xa4, 0x69,
	0x02, 0xab, 0xfe, 0xf4, 0x28, 0x1d, 0x95, 0x47, 0xde, 0x70, 0xc8, 0x37, 0x8b, 0x21, 0xaf, 0x48,
	0x78, 0x68, 0xae, 0xfc, 0xee, 0x32, 0x34, 0xd2, 0x45, 0x63, 0xcb, 0xd0, 0x48, 0x07, 0xc3, 0x3e,
	0x43, 0xab, 0x48, 0x87, 0x76, 0xe1, 0x96, 0x5f, 0x25, 0x3f, 0xf4, 0xe7, 0x15, 0x9d, 0x1d, 0xb9,
	0x3d, 0xf4, 0x82, 0xfc, 0x52, 0x84, 0x7d, 0x23, 0xb0, 0x9e, 0x07, 0xdb, 0xe9, 0x0d, 0xe8, 0x2a,
	0xdc, 0x94, 0xd3, 0x0e, 0x39, 0x52, 0x93, 0xa7, 0x7f, 0x28, 0x83, 0xdb, 0x7d, 0x1d, 0xa3, 0x3c,
	0x56, 0xae, 0x7d, 0xae, 0x41, 0x4d, 0x7e, 0xe5, 0x8c, 0xbe, 0x84, 0x96, 0xb1, 0x22, 0xb6, 0x52,
	0x1d, 0x87, 0x73, 0xf6, 0x94, 0x18, 0xa2, 0x9b, 0x61, 0x93, 0xaf, 0x5d, 0xde, 0xcf, 0x16, 0xbc,
	0x2b, 0x86, 0xc8, 0x38, 0xac, 0xe5, 0x8f, 0xed, 0xff, 0xdd, 0xb0, 0x75, 0xb8, 0x93, 0xd5, 0xdc,
	0xe9, 0x0d, 0xd8, 0x4f, 0x02, 0x0f, 0xff, 0xb9, 0xab, 0xf4, 0x05, 0x14, 0x98, 0xf5, 0x4e, 0x0a,
	0x6e, 0xe9, 0x2b, 0xb8, 0x1b, 0xa1, 0xb1, 0x52, 0x09, 0x2b, 0xb5, 0xba, 0x96, 0x9a, 0xfa, 0x2c,
	0x0e, 0x98, 0x95, 0x5b, 0x2f, 0x2b, 0x77, 0x29, 0xa7, 0xdc, 0xef, 0x04, 0x36, 0x4b, 0xab, 0x9a,
	0xce, 0xf6, 0x3d, 0xac, 0xf8, 0x7d, 0x9c, 0x7b, 0x40, 0xb6, 0x17, 0xfd, 0xb0, 0xfa, 0x9a, 0xcf,
	0xcb, 0xd0, 0xfb, 0xd0, 0x3c, 0xd1, 0x43, 0x9c, 0x1f, 0xc5, 0xec, 0x60, 0x77, 0xff, 0xc7, 0x38,
	0x20, 0x17, 0xe3, 0x80, 0xfc, 0x1e, 0x07, 0xe4, 0x7c, 0x12, 0xd4, 0x2e, 0x26, 0x41, 0xed, 0xd7,
	0x24, 0xa8, 0x7d, 0xdc, 0xca, 0xe1, 0x76, 0x4e, 0x3b, 0xd9, 0x57, 0xd2, 0x9e, 0x8d, 0xd0, 0x7c,
	0x6a, 0xb8, 0xf7, 0xf1, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0xa1, 0x53, 0x9b, 0xb6,
	0x05, 0x00, 0x00,
}

func (m *UniversitychainitPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UniversitychainitPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversitychainitPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *UniversitychainitPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversitychainitPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *UniversitychainitPacketData_ErasmusStudentPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversitychainitPacketData_ErasmusStudentPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ErasmusStudentPacket != nil {
		{
			size, err := m.ErasmusStudentPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *UniversitychainitPacketData_ErasmusIndexPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversitychainitPacketData_ErasmusIndexPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ErasmusIndexPacket != nil {
		{
			size, err := m.ErasmusIndexPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *UniversitychainitPacketData_EndErasmusPeriodRequestPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversitychainitPacketData_EndErasmusPeriodRequestPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.EndErasmusPeriodRequestPacket != nil {
		{
			size, err := m.EndErasmusPeriodRequestPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ErasmusStudentPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusStudentPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusStudentPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Student != nil {
		{
			size, err := m.Student.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusStudentPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusStudentPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusStudentPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StartingUniversityName) > 0 {
		i -= len(m.StartingUniversityName)
		copy(dAtA[i:], m.StartingUniversityName)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.StartingUniversityName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ForeignIndex) > 0 {
		i -= len(m.ForeignIndex)
		copy(dAtA[i:], m.ForeignIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ForeignIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusIndexPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusIndexPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusIndexPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ForeignIndex) > 0 {
		i -= len(m.ForeignIndex)
		copy(dAtA[i:], m.ForeignIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ForeignIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusIndexPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusIndexPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusIndexPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *EndErasmusPeriodRequestPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndErasmusPeriodRequestPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EndErasmusPeriodRequestPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ForeignIndex) > 0 {
		i -= len(m.ForeignIndex)
		copy(dAtA[i:], m.ForeignIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ForeignIndex)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DestinationUniversityName) > 0 {
		i -= len(m.DestinationUniversityName)
		copy(dAtA[i:], m.DestinationUniversityName)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.DestinationUniversityName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StartingUniversityName) > 0 {
		i -= len(m.StartingUniversityName)
		copy(dAtA[i:], m.StartingUniversityName)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.StartingUniversityName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EndErasmusPeriodRequestPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndErasmusPeriodRequestPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EndErasmusPeriodRequestPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HomeIndex) > 0 {
		i -= len(m.HomeIndex)
		copy(dAtA[i:], m.HomeIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.HomeIndex)))
		i--
		dAtA[i] = 0x12
	}
	if m.ErasmusData != nil {
		{
			size, err := m.ErasmusData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UniversitychainitPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *UniversitychainitPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *UniversitychainitPacketData_ErasmusStudentPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErasmusStudentPacket != nil {
		l = m.ErasmusStudentPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *UniversitychainitPacketData_ErasmusIndexPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErasmusIndexPacket != nil {
		l = m.ErasmusIndexPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *UniversitychainitPacketData_EndErasmusPeriodRequestPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EndErasmusPeriodRequestPacket != nil {
		l = m.EndErasmusPeriodRequestPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ErasmusStudentPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Student != nil {
		l = m.Student.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusStudentPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ForeignIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.StartingUniversityName)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusIndexPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ForeignIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusIndexPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *EndErasmusPeriodRequestPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StartingUniversityName)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.DestinationUniversityName)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ForeignIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *EndErasmusPeriodRequestPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErasmusData != nil {
		l = m.ErasmusData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.HomeIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UniversitychainitPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UniversitychainitPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UniversitychainitPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &UniversitychainitPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusStudentPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ErasmusStudentPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &UniversitychainitPacketData_ErasmusStudentPacket{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusIndexPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ErasmusIndexPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &UniversitychainitPacketData_ErasmusIndexPacket{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndErasmusPeriodRequestPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EndErasmusPeriodRequestPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &UniversitychainitPacketData_EndErasmusPeriodRequestPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusStudentPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusStudentPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusStudentPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Student == nil {
				m.Student = &StoredStudent{}
			}
			if err := m.Student.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusStudentPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusStudentPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusStudentPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartingUniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartingUniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusIndexPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusIndexPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusIndexPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusIndexPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusIndexPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusIndexPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndErasmusPeriodRequestPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndErasmusPeriodRequestPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndErasmusPeriodRequestPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartingUniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartingUniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationUniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationUniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndErasmusPeriodRequestPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndErasmusPeriodRequestPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndErasmusPeriodRequestPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ErasmusData == nil {
				m.ErasmusData = &ErasmusInfo{}
			}
			if err := m.ErasmusData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HomeIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HomeIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
