// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HubPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*HubPacketData_NoData
	//	*HubPacketData_ErasmusIndexPacket
	//	*HubPacketData_ErasmusStudentPacket
	Packet isHubPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *HubPacketData) Reset()         { *m = HubPacketData{} }
func (m *HubPacketData) String() string { return proto.CompactTextString(m) }
func (*HubPacketData) ProtoMessage()    {}
func (*HubPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{0}
}
func (m *HubPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HubPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HubPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HubPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HubPacketData.Merge(m, src)
}
func (m *HubPacketData) XXX_Size() int {
	return m.Size()
}
func (m *HubPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_HubPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_HubPacketData proto.InternalMessageInfo

type isHubPacketData_Packet interface {
	isHubPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type HubPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type HubPacketData_ErasmusIndexPacket struct {
	ErasmusIndexPacket *ErasmusIndexPacketData `protobuf:"bytes,3,opt,name=erasmusIndexPacket,proto3,oneof" json:"erasmusIndexPacket,omitempty"`
}
type HubPacketData_ErasmusStudentPacket struct {
	ErasmusStudentPacket *ErasmusStudentPacketData `protobuf:"bytes,2,opt,name=erasmusStudentPacket,proto3,oneof" json:"erasmusStudentPacket,omitempty"`
}

func (*HubPacketData_NoData) isHubPacketData_Packet()               {}
func (*HubPacketData_ErasmusIndexPacket) isHubPacketData_Packet()   {}
func (*HubPacketData_ErasmusStudentPacket) isHubPacketData_Packet() {}

func (m *HubPacketData) GetPacket() isHubPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *HubPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*HubPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *HubPacketData) GetErasmusIndexPacket() *ErasmusIndexPacketData {
	if x, ok := m.GetPacket().(*HubPacketData_ErasmusIndexPacket); ok {
		return x.ErasmusIndexPacket
	}
	return nil
}

func (m *HubPacketData) GetErasmusStudentPacket() *ErasmusStudentPacketData {
	if x, ok := m.GetPacket().(*HubPacketData_ErasmusStudentPacket); ok {
		return x.ErasmusStudentPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HubPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HubPacketData_NoData)(nil),
		(*HubPacketData_ErasmusIndexPacket)(nil),
		(*HubPacketData_ErasmusStudentPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// ErasmusStudentPacketData defines a struct for the packet payload
type ErasmusStudentPacketData struct {
	Student *StoredStudent `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
}

func (m *ErasmusStudentPacketData) Reset()         { *m = ErasmusStudentPacketData{} }
func (m *ErasmusStudentPacketData) String() string { return proto.CompactTextString(m) }
func (*ErasmusStudentPacketData) ProtoMessage()    {}
func (*ErasmusStudentPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{2}
}
func (m *ErasmusStudentPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusStudentPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusStudentPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusStudentPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusStudentPacketData.Merge(m, src)
}
func (m *ErasmusStudentPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusStudentPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusStudentPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusStudentPacketData proto.InternalMessageInfo

func (m *ErasmusStudentPacketData) GetStudent() *StoredStudent {
	if m != nil {
		return m.Student
	}
	return nil
}

// ErasmusStudentPacketAck defines a struct for the packet acknowledgment
type ErasmusStudentPacketAck struct {
	Index                  string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ForeignIndex           string `protobuf:"bytes,2,opt,name=foreign_index,json=foreignIndex,proto3" json:"foreign_index,omitempty"`
	StartingUniversityName string `protobuf:"bytes,3,opt,name=starting_university_name,json=startingUniversityName,proto3" json:"starting_university_name,omitempty"`
}

func (m *ErasmusStudentPacketAck) Reset()         { *m = ErasmusStudentPacketAck{} }
func (m *ErasmusStudentPacketAck) String() string { return proto.CompactTextString(m) }
func (*ErasmusStudentPacketAck) ProtoMessage()    {}
func (*ErasmusStudentPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{3}
}
func (m *ErasmusStudentPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusStudentPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusStudentPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusStudentPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusStudentPacketAck.Merge(m, src)
}
func (m *ErasmusStudentPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusStudentPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusStudentPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusStudentPacketAck proto.InternalMessageInfo

func (m *ErasmusStudentPacketAck) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ErasmusStudentPacketAck) GetForeignIndex() string {
	if m != nil {
		return m.ForeignIndex
	}
	return ""
}

func (m *ErasmusStudentPacketAck) GetStartingUniversityName() string {
	if m != nil {
		return m.StartingUniversityName
	}
	return ""
}

// ErasmusIndexPacketData defines a struct for the packet payload
type ErasmusIndexPacketData struct {
	Index        string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ForeignIndex string `protobuf:"bytes,2,opt,name=foreignIndex,proto3" json:"foreignIndex,omitempty"`
}

func (m *ErasmusIndexPacketData) Reset()         { *m = ErasmusIndexPacketData{} }
func (m *ErasmusIndexPacketData) String() string { return proto.CompactTextString(m) }
func (*ErasmusIndexPacketData) ProtoMessage()    {}
func (*ErasmusIndexPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{4}
}
func (m *ErasmusIndexPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusIndexPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusIndexPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusIndexPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusIndexPacketData.Merge(m, src)
}
func (m *ErasmusIndexPacketData) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusIndexPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusIndexPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusIndexPacketData proto.InternalMessageInfo

func (m *ErasmusIndexPacketData) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ErasmusIndexPacketData) GetForeignIndex() string {
	if m != nil {
		return m.ForeignIndex
	}
	return ""
}

// ErasmusIndexPacketAck defines a struct for the packet acknowledgment
type ErasmusIndexPacketAck struct {
}

func (m *ErasmusIndexPacketAck) Reset()         { *m = ErasmusIndexPacketAck{} }
func (m *ErasmusIndexPacketAck) String() string { return proto.CompactTextString(m) }
func (*ErasmusIndexPacketAck) ProtoMessage()    {}
func (*ErasmusIndexPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_604700aba5d55551, []int{5}
}
func (m *ErasmusIndexPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErasmusIndexPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErasmusIndexPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErasmusIndexPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErasmusIndexPacketAck.Merge(m, src)
}
func (m *ErasmusIndexPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *ErasmusIndexPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ErasmusIndexPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_ErasmusIndexPacketAck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HubPacketData)(nil), "hub.hub.HubPacketData")
	proto.RegisterType((*NoData)(nil), "hub.hub.NoData")
	proto.RegisterType((*ErasmusStudentPacketData)(nil), "hub.hub.ErasmusStudentPacketData")
	proto.RegisterType((*ErasmusStudentPacketAck)(nil), "hub.hub.ErasmusStudentPacketAck")
	proto.RegisterType((*ErasmusIndexPacketData)(nil), "hub.hub.ErasmusIndexPacketData")
	proto.RegisterType((*ErasmusIndexPacketAck)(nil), "hub.hub.ErasmusIndexPacketAck")
}

func init() { proto.RegisterFile("hub/packet.proto", fileDescriptor_604700aba5d55551) }

var fileDescriptor_604700aba5d55551 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x5b, 0xfe, 0xfc, 0x05, 0xae, 0x12, 0xcc, 0x04, 0xa1, 0x71, 0x51, 0x75, 0xdc, 0xc8,
	0xa6, 0x18, 0xdd, 0xb8, 0x85, 0x68, 0x82, 0x89, 0x21, 0x5a, 0x62, 0x4c, 0xdc, 0x34, 0x53, 0x18,
	0xa1, 0x21, 0x4c, 0x49, 0x67, 0xc6, 0xc0, 0x4b, 0x18, 0x1f, 0xcb, 0x25, 0x4b, 0x97, 0x06, 0x5e,
	0xc0, 0x47, 0x30, 0x9d, 0x0e, 0x24, 0x48, 0xd9, 0x10, 0x7a, 0xcf, 0x39, 0xdf, 0xdc, 0x39, 0x19,
	0x38, 0x18, 0xca, 0xa0, 0x31, 0x21, 0xbd, 0x11, 0x15, 0xee, 0x24, 0x8e, 0x44, 0x84, 0xf2, 0x43,
	0x19, 0xb8, 0x43, 0x19, 0x1c, 0xd9, 0x89, 0xc4, 0x45, 0x14, 0xd3, 0xbe, 0xcf, 0x85, 0xec, 0x53,
	0xa6, 0x2d, 0xf8, 0xc7, 0x84, 0x52, 0x5b, 0x06, 0x0f, 0x2a, 0x76, 0x43, 0x04, 0x41, 0x75, 0xb0,
	0x58, 0x94, 0xfc, 0xb3, 0xcd, 0x13, 0xf3, 0x7c, 0xef, 0xb2, 0xec, 0x6a, 0x8a, 0xdb, 0x51, 0xe3,
	0xb6, 0xe1, 0x69, 0x03, 0x7a, 0x04, 0x44, 0x63, 0xc2, 0xc7, 0x92, 0xdf, 0xb1, 0x3e, 0x9d, 0xa6,
	0x10, 0xfb, 0x9f, 0x8a, 0x1d, 0xaf, 0x63, 0xb7, 0x5b, 0x16, 0x8d, 0xc9, 0x08, 0xa3, 0x67, 0xa8,
	0xe8, 0x69, 0x37, 0xdd, 0x53, 0x43, 0x73, 0x0a, 0x7a, 0xfa, 0x17, 0xba, 0x61, 0xd2, 0xd8, 0x4c,
	0x40, 0xab, 0x00, 0x56, 0xda, 0x0d, 0x2e, 0x80, 0x95, 0xde, 0x04, 0xdf, 0x83, 0xbd, 0x8b, 0x83,
	0x2e, 0x20, 0xaf, 0x9b, 0xd2, 0x3d, 0x54, 0xd7, 0x67, 0x77, 0x55, 0x91, 0x3a, 0xe2, 0xad, 0x6c,
	0xf8, 0xdd, 0x84, 0x5a, 0x16, 0xae, 0xd9, 0x1b, 0xa1, 0x0a, 0xfc, 0x0f, 0x93, 0x5b, 0x2a, 0x56,
	0xd1, 0x4b, 0x3f, 0xd0, 0x19, 0x94, 0x5e, 0xa3, 0x98, 0x86, 0x03, 0xe6, 0xa7, 0x6a, 0x4e, 0xa9,
	0xfb, 0x7a, 0xa8, 0x7a, 0x41, 0xd7, 0x60, 0x73, 0x41, 0x62, 0x11, 0xb2, 0x81, 0x2f, 0x59, 0xf8,
	0x46, 0x63, 0x1e, 0x8a, 0x99, 0xcf, 0xc8, 0x98, 0xaa, 0xaa, 0x8b, 0x5e, 0x75, 0xa5, 0x3f, 0xad,
	0xe5, 0x0e, 0x19, 0x53, 0xec, 0x41, 0x35, 0xbb, 0xfb, 0x1d, 0xeb, 0x60, 0xd8, 0x38, 0x39, 0x6b,
	0x1b, 0x5c, 0x83, 0xc3, 0x6d, 0x66, 0xb3, 0x37, 0x6a, 0xd5, 0x3f, 0x17, 0x8e, 0x39, 0x5f, 0x38,
	0xe6, 0xf7, 0xc2, 0x31, 0x3f, 0x96, 0x8e, 0x31, 0x5f, 0x3a, 0xc6, 0xd7, 0xd2, 0x31, 0x5e, 0xca,
	0xc9, 0xe3, 0x9b, 0x36, 0x92, 0x5f, 0x31, 0x9b, 0x50, 0x1e, 0x58, 0xea, 0xe9, 0x5d, 0xfd, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x37, 0x7a, 0xdf, 0x6f, 0xb1, 0x02, 0x00, 0x00,
}

func (m *HubPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HubPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HubPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *HubPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HubPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *HubPacketData_ErasmusStudentPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HubPacketData_ErasmusStudentPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ErasmusStudentPacket != nil {
		{
			size, err := m.ErasmusStudentPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *HubPacketData_ErasmusIndexPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HubPacketData_ErasmusIndexPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ErasmusIndexPacket != nil {
		{
			size, err := m.ErasmusIndexPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ErasmusStudentPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusStudentPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusStudentPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Student != nil {
		{
			size, err := m.Student.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusStudentPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusStudentPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusStudentPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StartingUniversityName) > 0 {
		i -= len(m.StartingUniversityName)
		copy(dAtA[i:], m.StartingUniversityName)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.StartingUniversityName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ForeignIndex) > 0 {
		i -= len(m.ForeignIndex)
		copy(dAtA[i:], m.ForeignIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ForeignIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusIndexPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusIndexPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusIndexPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ForeignIndex) > 0 {
		i -= len(m.ForeignIndex)
		copy(dAtA[i:], m.ForeignIndex)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ForeignIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErasmusIndexPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErasmusIndexPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErasmusIndexPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HubPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *HubPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *HubPacketData_ErasmusStudentPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErasmusStudentPacket != nil {
		l = m.ErasmusStudentPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *HubPacketData_ErasmusIndexPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErasmusIndexPacket != nil {
		l = m.ErasmusIndexPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ErasmusStudentPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Student != nil {
		l = m.Student.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusStudentPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ForeignIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.StartingUniversityName)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusIndexPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ForeignIndex)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *ErasmusIndexPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HubPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HubPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HubPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &HubPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusStudentPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ErasmusStudentPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &HubPacketData_ErasmusStudentPacket{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusIndexPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ErasmusIndexPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &HubPacketData_ErasmusIndexPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusStudentPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusStudentPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusStudentPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Student == nil {
				m.Student = &StoredStudent{}
			}
			if err := m.Student.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusStudentPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusStudentPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusStudentPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartingUniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartingUniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusIndexPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusIndexPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusIndexPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForeignIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForeignIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErasmusIndexPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErasmusIndexPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErasmusIndexPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
