// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/stored_student.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StoredStudent struct {
	Index          string               `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	StudentData    *StudentInfo         `protobuf:"bytes,2,opt,name=studentData,proto3" json:"studentData,omitempty"`
	TranscriptData *TranscriptOfRecords `protobuf:"bytes,3,opt,name=transcriptData,proto3" json:"transcriptData,omitempty"`
	PersonalData   *PersonalInfo        `protobuf:"bytes,4,opt,name=personalData,proto3" json:"personalData,omitempty"`
	ResidenceData  *ResidenceInfo       `protobuf:"bytes,5,opt,name=residenceData,proto3" json:"residenceData,omitempty"`
	ContactData    *ContactInfo         `protobuf:"bytes,6,opt,name=contactData,proto3" json:"contactData,omitempty"`
	TaxesData      *TaxesInfo           `protobuf:"bytes,7,opt,name=taxesData,proto3" json:"taxesData,omitempty"`
	ErasmusData    *ErasmusInfo         `protobuf:"bytes,8,opt,name=erasmusData,proto3" json:"erasmusData,omitempty"`
}

func (m *StoredStudent) Reset()         { *m = StoredStudent{} }
func (m *StoredStudent) String() string { return proto.CompactTextString(m) }
func (*StoredStudent) ProtoMessage()    {}
func (*StoredStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_76deff3e7e9b928a, []int{0}
}
func (m *StoredStudent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredStudent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredStudent.Merge(m, src)
}
func (m *StoredStudent) XXX_Size() int {
	return m.Size()
}
func (m *StoredStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredStudent.DiscardUnknown(m)
}

var xxx_messageInfo_StoredStudent proto.InternalMessageInfo

func (m *StoredStudent) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *StoredStudent) GetStudentData() *StudentInfo {
	if m != nil {
		return m.StudentData
	}
	return nil
}

func (m *StoredStudent) GetTranscriptData() *TranscriptOfRecords {
	if m != nil {
		return m.TranscriptData
	}
	return nil
}

func (m *StoredStudent) GetPersonalData() *PersonalInfo {
	if m != nil {
		return m.PersonalData
	}
	return nil
}

func (m *StoredStudent) GetResidenceData() *ResidenceInfo {
	if m != nil {
		return m.ResidenceData
	}
	return nil
}

func (m *StoredStudent) GetContactData() *ContactInfo {
	if m != nil {
		return m.ContactData
	}
	return nil
}

func (m *StoredStudent) GetTaxesData() *TaxesInfo {
	if m != nil {
		return m.TaxesData
	}
	return nil
}

func (m *StoredStudent) GetErasmusData() *ErasmusInfo {
	if m != nil {
		return m.ErasmusData
	}
	return nil
}

func init() {
	proto.RegisterType((*StoredStudent)(nil), "hub.hub.StoredStudent")
}

func init() { proto.RegisterFile("hub/stored_student.proto", fileDescriptor_76deff3e7e9b928a) }

var fileDescriptor_76deff3e7e9b928a = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x99, 0x08, 0x48, 0x11, 0x4d, 0x1a, 0x44, 0x42, 0xcc, 0x24, 0x9e, 0xf0, 0x32, 0x8c,
	0x26, 0x26, 0x26, 0x9e, 0x14, 0x0f, 0x9e, 0x34, 0xc3, 0x93, 0x97, 0xa5, 0xdb, 0xba, 0xb0, 0x44,
	0xdb, 0xa5, 0xed, 0x12, 0xfc, 0x2f, 0xfc, 0x8b, 0x3c, 0x7b, 0xe4, 0xe8, 0xd1, 0xc0, 0x3f, 0x62,
	0xf6, 0x5a, 0x46, 0xc1, 0x23, 0xfd, 0xbe, 0xdf, 0xfb, 0xf8, 0xde, 0x1b, 0xea, 0x4d, 0xf3, 0x70,
	0x24, 0x15, 0x17, 0x34, 0x0e, 0xa4, 0xca, 0x63, 0xca, 0x94, 0x97, 0x09, 0xae, 0x38, 0x6e, 0x4c,
	0xf3, 0xd0, 0x9b, 0xe6, 0x61, 0xbf, 0xab, 0x2d, 0xa0, 0x05, 0x29, 0x4b, 0xb8, 0x36, 0xf4, 0x4f,
	0x8b, 0x77, 0x25, 0x08, 0x93, 0x91, 0x48, 0x33, 0x15, 0xf0, 0x24, 0x10, 0x34, 0xe2, 0x22, 0x96,
	0xc6, 0x70, 0x5c, 0x18, 0x32, 0x2a, 0x24, 0x67, 0xe4, 0xcd, 0x26, 0x21, 0x54, 0x50, 0x99, 0xc6,
	0x94, 0x45, 0xd4, 0x56, 0x20, 0x2b, 0xe2, 0x4c, 0x91, 0x68, 0x23, 0xab, 0x03, 0x59, 0x64, 0x46,
	0xe5, 0x3f, 0x37, 0x15, 0x44, 0xbe, 0xe7, 0xf6, 0xfb, 0xd9, 0x57, 0x15, 0xb5, 0x27, 0xd0, 0x69,
	0xa2, 0xff, 0x36, 0xee, 0xa0, 0x5a, 0xca, 0x62, 0x3a, 0xeb, 0x39, 0x03, 0x67, 0xd8, 0xf4, 0xf5,
	0x0f, 0x7c, 0x8d, 0x5a, 0xa6, 0xd7, 0x98, 0x28, 0xd2, 0xdb, 0x19, 0x38, 0xc3, 0xd6, 0x65, 0xc7,
	0x33, 0xc5, 0x3d, 0x03, 0x3f, 0xb2, 0x84, 0xfb, 0xb6, 0x11, 0x8f, 0xd1, 0xc1, 0xba, 0x37, 0xa0,
	0x55, 0x40, 0x4f, 0x4a, 0xf4, 0xa5, 0x94, 0x9f, 0x12, 0x5f, 0x2f, 0xc5, 0xdf, 0x62, 0xf0, 0x0d,
	0xda, 0x5f, 0x2d, 0x07, 0x66, 0xec, 0xc2, 0x8c, 0xa3, 0x72, 0xc6, 0xb3, 0x11, 0x21, 0x7f, 0xc3,
	0x8a, 0x6f, 0x51, 0xbb, 0x5c, 0x1f, 0xb0, 0x35, 0x60, 0xbb, 0x25, 0xeb, 0xaf, 0x54, 0x80, 0x37,
	0xcd, 0x45, 0x6d, 0xb3, 0x62, 0x60, 0xeb, 0x5b, 0xb5, 0xef, 0xb5, 0xa6, 0x6b, 0x5b, 0x46, 0x7c,
	0x81, 0x9a, 0x70, 0x02, 0xa0, 0x1a, 0x40, 0xe1, 0x75, 0xe3, 0x42, 0x01, 0x66, 0x6d, 0x2a, 0x92,
	0xcc, 0x79, 0x80, 0xd9, 0xdb, 0x4a, 0x7a, 0xd0, 0x9a, 0x4e, 0xb2, 0x8c, 0x77, 0xe7, 0xdf, 0x0b,
	0xd7, 0x99, 0x2f, 0x5c, 0xe7, 0x77, 0xe1, 0x3a, 0x9f, 0x4b, 0xb7, 0x32, 0x5f, 0xba, 0x95, 0x9f,
	0xa5, 0x5b, 0x79, 0x3d, 0x2c, 0x4e, 0x3e, 0x1b, 0xc1, 0xe7, 0xf0, 0x91, 0x51, 0x19, 0xd6, 0xe1,
	0xe4, 0x57, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x66, 0x33, 0x0e, 0xc9, 0x02, 0x00, 0x00,
}

func (m *StoredStudent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredStudent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredStudent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ErasmusData != nil {
		{
			size, err := m.ErasmusData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.TaxesData != nil {
		{
			size, err := m.TaxesData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ContactData != nil {
		{
			size, err := m.ContactData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ResidenceData != nil {
		{
			size, err := m.ResidenceData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.PersonalData != nil {
		{
			size, err := m.PersonalData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.TranscriptData != nil {
		{
			size, err := m.TranscriptData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StudentData != nil {
		{
			size, err := m.StudentData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintStoredStudent(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStoredStudent(dAtA []byte, offset int, v uint64) int {
	offset -= sovStoredStudent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredStudent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.StudentData != nil {
		l = m.StudentData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.TranscriptData != nil {
		l = m.TranscriptData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.PersonalData != nil {
		l = m.PersonalData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.ResidenceData != nil {
		l = m.ResidenceData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.ContactData != nil {
		l = m.ContactData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.TaxesData != nil {
		l = m.TaxesData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	if m.ErasmusData != nil {
		l = m.ErasmusData.Size()
		n += 1 + l + sovStoredStudent(uint64(l))
	}
	return n
}

func sovStoredStudent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStoredStudent(x uint64) (n int) {
	return sovStoredStudent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredStudent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStoredStudent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredStudent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredStudent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StudentData == nil {
				m.StudentData = &StudentInfo{}
			}
			if err := m.StudentData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TranscriptData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TranscriptData == nil {
				m.TranscriptData = &TranscriptOfRecords{}
			}
			if err := m.TranscriptData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PersonalData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PersonalData == nil {
				m.PersonalData = &PersonalInfo{}
			}
			if err := m.PersonalData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResidenceData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ResidenceData == nil {
				m.ResidenceData = &ResidenceInfo{}
			}
			if err := m.ResidenceData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContactData == nil {
				m.ContactData = &ContactInfo{}
			}
			if err := m.ContactData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxesData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaxesData == nil {
				m.TaxesData = &TaxesInfo{}
			}
			if err := m.TaxesData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ErasmusData == nil {
				m.ErasmusData = &ErasmusInfo{}
			}
			if err := m.ErasmusData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStoredStudent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStoredStudent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStoredStudent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStoredStudent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredStudent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStoredStudent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStoredStudent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStoredStudent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStoredStudent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStoredStudent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStoredStudent = fmt.Errorf("proto: unexpected end of group")
)
