// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainde/counters_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CountersInfo struct {
	PacketsRetriesStartErasmus   []int32 `protobuf:"varint,1,rep,packed,name=PacketsRetriesStartErasmus,proto3" json:"PacketsRetriesStartErasmus,omitempty"`
	AcksReceivedStartErasmus     int32   `protobuf:"varint,2,opt,name=AcksReceivedStartErasmus,proto3" json:"AcksReceivedStartErasmus,omitempty"`
	RetryNumberOperations        int32   `protobuf:"varint,3,opt,name=retryNumberOperations,proto3" json:"retryNumberOperations,omitempty"`
	MaximumNumberRetries         int32   `protobuf:"varint,4,opt,name=maximumNumberRetries,proto3" json:"maximumNumberRetries,omitempty"`
	ErrorAcksOrTimeoutsReceived  int32   `protobuf:"varint,5,opt,name=errorAcksOrTimeoutsReceived,proto3" json:"errorAcksOrTimeoutsReceived,omitempty"`
	RevertErasmusCareerCompleted bool    `protobuf:"varint,6,opt,name=revertErasmusCareerCompleted,proto3" json:"revertErasmusCareerCompleted,omitempty"`
}

func (m *CountersInfo) Reset()         { *m = CountersInfo{} }
func (m *CountersInfo) String() string { return proto.CompactTextString(m) }
func (*CountersInfo) ProtoMessage()    {}
func (*CountersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8166123c761381, []int{0}
}
func (m *CountersInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CountersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CountersInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CountersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountersInfo.Merge(m, src)
}
func (m *CountersInfo) XXX_Size() int {
	return m.Size()
}
func (m *CountersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CountersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CountersInfo proto.InternalMessageInfo

func (m *CountersInfo) GetPacketsRetriesStartErasmus() []int32 {
	if m != nil {
		return m.PacketsRetriesStartErasmus
	}
	return nil
}

func (m *CountersInfo) GetAcksReceivedStartErasmus() int32 {
	if m != nil {
		return m.AcksReceivedStartErasmus
	}
	return 0
}

func (m *CountersInfo) GetRetryNumberOperations() int32 {
	if m != nil {
		return m.RetryNumberOperations
	}
	return 0
}

func (m *CountersInfo) GetMaximumNumberRetries() int32 {
	if m != nil {
		return m.MaximumNumberRetries
	}
	return 0
}

func (m *CountersInfo) GetErrorAcksOrTimeoutsReceived() int32 {
	if m != nil {
		return m.ErrorAcksOrTimeoutsReceived
	}
	return 0
}

func (m *CountersInfo) GetRevertErasmusCareerCompleted() bool {
	if m != nil {
		return m.RevertErasmusCareerCompleted
	}
	return false
}

func init() {
	proto.RegisterType((*CountersInfo)(nil), "university_chain_de.universitychainde.CountersInfo")
}

func init() {
	proto.RegisterFile("universitychainde/counters_info.proto", fileDescriptor_cb8166123c761381)
}

var fileDescriptor_cb8166123c761381 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0x72, 0x41,
	0x18, 0x86, 0x1d, 0xfd, 0x95, 0x9f, 0xa1, 0xd5, 0x50, 0x30, 0x54, 0x0c, 0x12, 0x04, 0x6e, 0x52,
	0xa8, 0x56, 0x2d, 0xa2, 0x94, 0x88, 0x36, 0x19, 0xa7, 0x56, 0x6d, 0x64, 0x3c, 0xe7, 0x93, 0x06,
	0x9b, 0x99, 0xc3, 0x37, 0xdf, 0x88, 0xde, 0x45, 0x97, 0xd5, 0xd2, 0x65, 0xcb, 0xd0, 0xbb, 0x68,
	0x15, 0x9d, 0x44, 0x0a, 0xcd, 0xf5, 0xfb, 0x3c, 0xf0, 0xc0, 0xcb, 0x0f, 0xa3, 0x33, 0x23, 0xc0,
	0x60, 0x68, 0x92, 0x3e, 0x69, 0xe3, 0x32, 0x68, 0xa5, 0x3e, 0x3a, 0x02, 0x0c, 0x3d, 0xe3, 0x06,
	0xbe, 0x99, 0xa3, 0x27, 0x2f, 0x7e, 0x60, 0xbd, 0x82, 0xeb, 0x65, 0xd0, 0x5c, 0x51, 0x0f, 0x3e,
	0xca, 0x7c, 0xab, 0xb3, 0xd0, 0x6f, 0xdc, 0xc0, 0x8b, 0x73, 0xbe, 0x7b, 0xa7, 0xd3, 0x21, 0x50,
	0x48, 0x80, 0xd0, 0x40, 0xb8, 0x27, 0x8d, 0x74, 0x85, 0x3a, 0xd8, 0x18, 0x24, 0xab, 0x57, 0x1a,
	0xd5, 0x64, 0x03, 0x21, 0xce, 0xb8, 0xbc, 0x4c, 0x87, 0x21, 0x81, 0x14, 0xcc, 0x08, 0xb2, 0x5f,
	0x76, 0xb9, 0xce, 0x1a, 0xd5, 0xe4, 0xcf, 0x5d, 0x9c, 0xf2, 0x1d, 0x04, 0xc2, 0xc9, 0x6d, 0xb4,
	0x7d, 0xc0, 0x6e, 0x0e, 0xa8, 0xc9, 0x78, 0x17, 0x64, 0xa5, 0x10, 0xd7, 0x8f, 0xe2, 0x98, 0x6f,
	0x5b, 0x3d, 0x36, 0x36, 0xda, 0xef, 0x69, 0x51, 0x25, 0xff, 0x15, 0xd2, 0xda, 0x4d, 0x5c, 0xf0,
	0x3d, 0x40, 0xf4, 0xf8, 0x95, 0xd2, 0xc5, 0x07, 0x63, 0xc1, 0x47, 0x5a, 0x46, 0xc9, 0x6a, 0xa1,
	0x6e, 0x42, 0x44, 0x9b, 0xef, 0x23, 0x8c, 0x60, 0x19, 0xdf, 0xd1, 0x08, 0x80, 0x1d, 0x6f, 0xf3,
	0x67, 0x20, 0xc8, 0x64, 0xad, 0xce, 0x1a, 0xff, 0x93, 0x8d, 0x4c, 0xfb, 0xfa, 0x75, 0xa6, 0xd8,
	0x74, 0xa6, 0xd8, 0xfb, 0x4c, 0xb1, 0x97, 0xb9, 0x2a, 0x4d, 0xe7, 0xaa, 0xf4, 0x36, 0x57, 0xa5,
	0xc7, 0xa3, 0x35, 0xef, 0xb5, 0xc6, 0xad, 0xd5, 0xeb, 0x69, 0x92, 0x43, 0xe8, 0xd7, 0x8a, 0xcf,
	0x4f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x54, 0x36, 0x28, 0x1c, 0x02, 0x00, 0x00,
}

func (m *CountersInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CountersInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CountersInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevertErasmusCareerCompleted {
		i--
		if m.RevertErasmusCareerCompleted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.ErrorAcksOrTimeoutsReceived != 0 {
		i = encodeVarintCountersInfo(dAtA, i, uint64(m.ErrorAcksOrTimeoutsReceived))
		i--
		dAtA[i] = 0x28
	}
	if m.MaximumNumberRetries != 0 {
		i = encodeVarintCountersInfo(dAtA, i, uint64(m.MaximumNumberRetries))
		i--
		dAtA[i] = 0x20
	}
	if m.RetryNumberOperations != 0 {
		i = encodeVarintCountersInfo(dAtA, i, uint64(m.RetryNumberOperations))
		i--
		dAtA[i] = 0x18
	}
	if m.AcksReceivedStartErasmus != 0 {
		i = encodeVarintCountersInfo(dAtA, i, uint64(m.AcksReceivedStartErasmus))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PacketsRetriesStartErasmus) > 0 {
		dAtA2 := make([]byte, len(m.PacketsRetriesStartErasmus)*10)
		var j1 int
		for _, num1 := range m.PacketsRetriesStartErasmus {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintCountersInfo(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCountersInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovCountersInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CountersInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PacketsRetriesStartErasmus) > 0 {
		l = 0
		for _, e := range m.PacketsRetriesStartErasmus {
			l += sovCountersInfo(uint64(e))
		}
		n += 1 + sovCountersInfo(uint64(l)) + l
	}
	if m.AcksReceivedStartErasmus != 0 {
		n += 1 + sovCountersInfo(uint64(m.AcksReceivedStartErasmus))
	}
	if m.RetryNumberOperations != 0 {
		n += 1 + sovCountersInfo(uint64(m.RetryNumberOperations))
	}
	if m.MaximumNumberRetries != 0 {
		n += 1 + sovCountersInfo(uint64(m.MaximumNumberRetries))
	}
	if m.ErrorAcksOrTimeoutsReceived != 0 {
		n += 1 + sovCountersInfo(uint64(m.ErrorAcksOrTimeoutsReceived))
	}
	if m.RevertErasmusCareerCompleted {
		n += 2
	}
	return n
}

func sovCountersInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCountersInfo(x uint64) (n int) {
	return sovCountersInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CountersInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCountersInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CountersInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CountersInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCountersInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PacketsRetriesStartErasmus = append(m.PacketsRetriesStartErasmus, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCountersInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCountersInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCountersInfo
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PacketsRetriesStartErasmus) == 0 {
					m.PacketsRetriesStartErasmus = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCountersInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PacketsRetriesStartErasmus = append(m.PacketsRetriesStartErasmus, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketsRetriesStartErasmus", wireType)
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcksReceivedStartErasmus", wireType)
			}
			m.AcksReceivedStartErasmus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcksReceivedStartErasmus |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryNumberOperations", wireType)
			}
			m.RetryNumberOperations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetryNumberOperations |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumNumberRetries", wireType)
			}
			m.MaximumNumberRetries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaximumNumberRetries |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorAcksOrTimeoutsReceived", wireType)
			}
			m.ErrorAcksOrTimeoutsReceived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorAcksOrTimeoutsReceived |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevertErasmusCareerCompleted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RevertErasmusCareerCompleted = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCountersInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCountersInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCountersInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCountersInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCountersInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCountersInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCountersInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCountersInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCountersInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCountersInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCountersInfo = fmt.Errorf("proto: unexpected end of group")
)
