// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainde/student_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StudentInfo struct {
	Name                     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname                  string  `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	CourseType               string  `protobuf:"bytes,3,opt,name=courseType,proto3" json:"courseType,omitempty"`
	CourseOfStudy            string  `protobuf:"bytes,4,opt,name=courseOfStudy,proto3" json:"courseOfStudy,omitempty"`
	Status                   string  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentYearOfStudy       uint32  `protobuf:"varint,6,opt,name=currentYearOfStudy,proto3" json:"currentYearOfStudy,omitempty"`
	OutOfCourse              bool    `protobuf:"varint,7,opt,name=outOfCourse,proto3" json:"outOfCourse,omitempty"`
	NumberOfYearsOutOfCourse uint32  `protobuf:"varint,8,opt,name=numberOfYearsOutOfCourse,proto3" json:"numberOfYearsOutOfCourse,omitempty"`
	StudentKey               string  `protobuf:"bytes,9,opt,name=studentKey,proto3" json:"studentKey,omitempty"`
	CompleteInformation      []int32 `protobuf:"varint,10,rep,packed,name=completeInformation,proto3" json:"completeInformation,omitempty"`
	UniversityName           string  `protobuf:"bytes,11,opt,name=universityName,proto3" json:"universityName,omitempty"`
	ChainName                string  `protobuf:"bytes,12,opt,name=chainName,proto3" json:"chainName,omitempty"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e804b94666adf1c, []int{0}
}
func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return m.Size()
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *StudentInfo) GetCourseType() string {
	if m != nil {
		return m.CourseType
	}
	return ""
}

func (m *StudentInfo) GetCourseOfStudy() string {
	if m != nil {
		return m.CourseOfStudy
	}
	return ""
}

func (m *StudentInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StudentInfo) GetCurrentYearOfStudy() uint32 {
	if m != nil {
		return m.CurrentYearOfStudy
	}
	return 0
}

func (m *StudentInfo) GetOutOfCourse() bool {
	if m != nil {
		return m.OutOfCourse
	}
	return false
}

func (m *StudentInfo) GetNumberOfYearsOutOfCourse() uint32 {
	if m != nil {
		return m.NumberOfYearsOutOfCourse
	}
	return 0
}

func (m *StudentInfo) GetStudentKey() string {
	if m != nil {
		return m.StudentKey
	}
	return ""
}

func (m *StudentInfo) GetCompleteInformation() []int32 {
	if m != nil {
		return m.CompleteInformation
	}
	return nil
}

func (m *StudentInfo) GetUniversityName() string {
	if m != nil {
		return m.UniversityName
	}
	return ""
}

func (m *StudentInfo) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func init() {
	proto.RegisterType((*StudentInfo)(nil), "university_chain_de.universitychainde.StudentInfo")
}

func init() {
	proto.RegisterFile("universitychainde/student_info.proto", fileDescriptor_4e804b94666adf1c)
}

var fileDescriptor_4e804b94666adf1c = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4a, 0xeb, 0x50,
	0x10, 0xc6, 0x9b, 0xdb, 0xff, 0xd3, 0xdb, 0xbb, 0x38, 0x17, 0xe4, 0x2c, 0x24, 0x04, 0xa9, 0x92,
	0x8d, 0xad, 0xe0, 0xce, 0xa5, 0x2e, 0x44, 0x04, 0x03, 0xd1, 0x8d, 0x6e, 0x4a, 0x9a, 0x4e, 0x30,
	0x60, 0xce, 0x09, 0xe7, 0x8f, 0x98, 0xb7, 0xf0, 0x8d, 0xdc, 0xba, 0xec, 0xd2, 0xa5, 0xb4, 0x2f,
	0x22, 0x99, 0xb6, 0xa4, 0xda, 0xba, 0xcb, 0xfc, 0xbe, 0x6f, 0xbe, 0x70, 0x66, 0x06, 0x06, 0x56,
	0xa4, 0xcf, 0xa8, 0x74, 0x6a, 0x8a, 0xf8, 0x31, 0x4a, 0xc5, 0x14, 0x47, 0xda, 0xd8, 0x29, 0x0a,
	0x33, 0x4e, 0x45, 0x22, 0x87, 0xb9, 0x92, 0x46, 0xb2, 0xc3, 0xca, 0x35, 0x26, 0xdb, 0x78, 0x8a,
	0xc3, 0xad, 0xce, 0x83, 0xb7, 0x3a, 0xf4, 0x6e, 0x97, 0xdd, 0x57, 0x22, 0x91, 0x8c, 0x41, 0x43,
	0x44, 0x19, 0x72, 0xc7, 0x73, 0xfc, 0x6e, 0x48, 0xdf, 0x8c, 0x43, 0x5b, 0x5b, 0x45, 0xf8, 0x0f,
	0xe1, 0x75, 0xc9, 0x5c, 0x80, 0x58, 0x5a, 0xa5, 0xf1, 0xae, 0xc8, 0x91, 0xd7, 0x49, 0xdc, 0x20,
	0x6c, 0x00, 0xfd, 0x65, 0x15, 0x24, 0xe5, 0x4f, 0x0a, 0xde, 0x20, 0xcb, 0x77, 0xc8, 0xf6, 0xa0,
	0xa5, 0x4d, 0x64, 0xac, 0xe6, 0x4d, 0x92, 0x57, 0x15, 0x1b, 0x02, 0x8b, 0xad, 0x52, 0x28, 0xcc,
	0x3d, 0x46, 0x6a, 0x1d, 0xd1, 0xf2, 0x1c, 0xbf, 0x1f, 0xee, 0x50, 0x98, 0x07, 0x3d, 0x69, 0x4d,
	0x90, 0x5c, 0x50, 0x3a, 0x6f, 0x7b, 0x8e, 0xdf, 0x09, 0x37, 0x11, 0x3b, 0x03, 0x2e, 0x6c, 0x36,
	0x41, 0x15, 0x24, 0x65, 0xa3, 0x0e, 0x36, 0xec, 0x1d, 0xca, 0xfd, 0x55, 0x2f, 0xdf, 0xba, 0x1a,
	0xf3, 0x35, 0x16, 0xbc, 0xbb, 0x7c, 0x6b, 0x45, 0xd8, 0x09, 0xfc, 0x8f, 0x65, 0x96, 0x3f, 0xa1,
	0xc1, 0x72, 0x92, 0x2a, 0x8b, 0x4c, 0x2a, 0x05, 0x07, 0xaf, 0xee, 0x37, 0xc3, 0x5d, 0x12, 0x3b,
	0x82, 0x7f, 0xd5, 0x42, 0x6e, 0xca, 0xf1, 0xf6, 0x28, 0xf5, 0x07, 0x65, 0xfb, 0xd0, 0xa5, 0x75,
	0x91, 0xe5, 0x2f, 0x59, 0x2a, 0x70, 0x7e, 0xf9, 0x3e, 0x77, 0x9d, 0xd9, 0xdc, 0x75, 0x3e, 0xe7,
	0xae, 0xf3, 0xba, 0x70, 0x6b, 0xb3, 0x85, 0x5b, 0xfb, 0x58, 0xb8, 0xb5, 0x87, 0xe3, 0x1d, 0x27,
	0x30, 0x7a, 0x19, 0x6d, 0x9f, 0x8f, 0x29, 0x72, 0xd4, 0x93, 0x16, 0x1d, 0xce, 0xe9, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x45, 0x9a, 0xe9, 0x60, 0x02, 0x00, 0x00,
}

func (m *StudentInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StudentInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StudentInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.UniversityName) > 0 {
		i -= len(m.UniversityName)
		copy(dAtA[i:], m.UniversityName)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.UniversityName)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.CompleteInformation) > 0 {
		dAtA2 := make([]byte, len(m.CompleteInformation)*10)
		var j1 int
		for _, num1 := range m.CompleteInformation {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintStudentInfo(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x52
	}
	if len(m.StudentKey) > 0 {
		i -= len(m.StudentKey)
		copy(dAtA[i:], m.StudentKey)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.StudentKey)))
		i--
		dAtA[i] = 0x4a
	}
	if m.NumberOfYearsOutOfCourse != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.NumberOfYearsOutOfCourse))
		i--
		dAtA[i] = 0x40
	}
	if m.OutOfCourse {
		i--
		if m.OutOfCourse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.CurrentYearOfStudy != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.CurrentYearOfStudy))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CourseOfStudy) > 0 {
		i -= len(m.CourseOfStudy)
		copy(dAtA[i:], m.CourseOfStudy)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.CourseOfStudy)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CourseType) > 0 {
		i -= len(m.CourseType)
		copy(dAtA[i:], m.CourseType)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.CourseType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Surname) > 0 {
		i -= len(m.Surname)
		copy(dAtA[i:], m.Surname)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.Surname)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStudentInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovStudentInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StudentInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.Surname)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.CourseType)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.CourseOfStudy)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	if m.CurrentYearOfStudy != 0 {
		n += 1 + sovStudentInfo(uint64(m.CurrentYearOfStudy))
	}
	if m.OutOfCourse {
		n += 2
	}
	if m.NumberOfYearsOutOfCourse != 0 {
		n += 1 + sovStudentInfo(uint64(m.NumberOfYearsOutOfCourse))
	}
	l = len(m.StudentKey)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	if len(m.CompleteInformation) > 0 {
		l = 0
		for _, e := range m.CompleteInformation {
			l += sovStudentInfo(uint64(e))
		}
		n += 1 + sovStudentInfo(uint64(l)) + l
	}
	l = len(m.UniversityName)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	return n
}

func sovStudentInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStudentInfo(x uint64) (n int) {
	return sovStudentInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StudentInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStudentInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StudentInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StudentInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Surname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Surname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CourseType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseOfStudy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CourseOfStudy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentYearOfStudy", wireType)
			}
			m.CurrentYearOfStudy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentYearOfStudy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutOfCourse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OutOfCourse = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumberOfYearsOutOfCourse", wireType)
			}
			m.NumberOfYearsOutOfCourse = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumberOfYearsOutOfCourse |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StudentKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStudentInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CompleteInformation = append(m.CompleteInformation, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStudentInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthStudentInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthStudentInfo
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.CompleteInformation) == 0 {
					m.CompleteInformation = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStudentInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CompleteInformation = append(m.CompleteInformation, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CompleteInformation", wireType)
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStudentInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStudentInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStudentInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStudentInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStudentInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStudentInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStudentInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStudentInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStudentInfo = fmt.Errorf("proto: unexpected end of group")
)
